name: Build Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        chapter:
          - name: chap1
            folder: Chapter01
          - name: chap2
            folder: Chapter02
          - name: chap3
            folder: Chapter03
          - name: chap4
            folder: Chapter04
          - name: chap-nn
            folder: ChapterNN
          - name: chap5
            folder: Chapter05
          - name: chap6
            folder: Chapter06
    runs-on: ubuntu-latest
    name: Image ${{ matrix.chapter.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build Image
        id: build
        run: |
          cd docker
          docker build . --target ${{ matrix.chapter.name }} \
            --build-arg branch=${{ steps.extract_branch.outputs.branch }} \
            -t graph-machine-learning:latest --no-cache 

      - name: Test Image
        id: tests
        run: |
          
          mkdir -p data
          chmod -R 777 data 
          docker run \
            --rm --detach -v "$(pwd)/data:/data" \
            --name graph-machine-learning-box \
            graph-machine-learning:latest
                    
          # Run tests
          cd docker

          ./tests.sh ${{ matrix.chapter.folder }}